from flask import Flask, jsonify
import game_schedule_scrapper
import scrapper
import model


## WORK IN PROGRESS ##



app = Flask(__name__)

@app.route('/game-schedule', methods=['GET'])
def game_schedule():
    SCHEDULE = game_schedule_scrapper.fetch_game_schedule()
    return SCHEDULE

@app.route('/ml-results', methods=['GET'])
def get_predictions():
    # logic for another script
    data = {
        "message": "Data generated by script2"
    }
    return jsonify(data)

if __name__ == '__main__':
    app.run()
